title: Derek Stride
email: djgstride@gmail.com

plugins:
  - jekyll-feed
  - jekyll-postcss

feed:
  path: rss.xml

include:
  - '_pages'

exclude:
  - "*.config.js"
  - "package*.json"
  - "node_modules"
