title: derekstride
author: derekstride
email: djgstride@gmail.com
url: https://derek.stride.host

plugins:
  - jekyll-feed
  - jekyll-postcss

feed:
  path: /posts/rss.xml
  collections:
    books:
      path: /books/rss.xml

exclude:
  - "*.config.js"
  - "package*.json"
  - "node_modules"

collections:
  posts:
    output: true
    permalink: /:collection/:title
  books:
    output: true
    permalink: /:collection/:title
