# Site settings
title: Derek Stride
email: djgstride@gmail.com
description: "See | Solve | Save"

# Build settings
highlighter: pygments
kramdown:
  input: GFM
permalink: pretty

port: 3000

sass:
  sass_dir: assets/css
  style: :nested
