title: derekstride
author: derekstride
email: derek@stride.host
url: https://derek.stride.host

defaults:
  - scope:
      path: "assets/pdfs"
    values:
      pdf: true

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-graphviz

feed:
  path: /posts/rss.xml
  collections:
    books:
      path: /books/rss.xml
    talks:
      path: /talks/rss.xml

exclude:
  - "*.config.js"
  - "package*.json"
  - "node_modules"
  - "bin"
  - "graphs"
  - "tmp"

collections:
  posts:
    output: true
    permalink: /:collection/:title
  books:
    output: true
    permalink: /:collection/:title
  talks:
    output: true
    permalink: /:collection/:title
