# Build settings
highlighter: pygments
kramdown:
  input: GFM
permalink: pretty

safe: true
lsi: false
port: 3000

sass:
  sass_dir: assets/css
  style: :nested

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      heading:  "Introduction"
      layout:   "default"
  -
    scope:
      path:   "projects"
      type:   "pages"
    values:
      layout: "project"
      author: "Derek Stride"
  -
    scope:
      path: ""
      type: "posts"
    values:
      heading:  "Introduction"
      layout:   "wrapper"
