title: derekstride
author: derekstride
email: djgstride@gmail.com
url: https://derek.stride.host

plugins:
  - jekyll-feed
  - jekyll-postcss

feed:
  path: rss.xml

include:
  - '_pages'

exclude:
  - "*.config.js"
  - "package*.json"
  - "node_modules"
  - "bin"
  - "graphs"
  - "tmp"

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title
  books:
    output: true
    permalink: /:collection/:name
