# Site settings
title: Derek Stride
email: djgstride@gmail.com
tagline: "See | Solve | Save"

# Build settings
highlighter: pygments
kramdown:
  input: GFM
permalink: pretty

safe: true
lsi: false
port: 3000

sass:
  sass_dir: assets/css
  style: :nested
